Add additional events when to clear waveform
Bible-Translation-Tools/otter pull request #1010
Opened 2024-02-02 11:37 UTC by mXaln

Added `BeforeNavigationEvent` to track when to clear waveform in Translation mode. Attempts to clean waveform will happen when going to Home page, other chapter and other step.

2024-02-02 13:33 UTC, AnonymousWalker requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010#-Npe-ktl2EJy-hZl6Ywz:-Npe-ktl2EJy-hZl6Yx-:b-rkysqg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/855a200659f031e8355b777cf8e97268dc848bee/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L58)):*
> ```Kotlin
>             val homePage = find<HomePage2>()
>             fire(NavigationRequestEvent(homePage))
>         }
> ```

`NavigationRequestEvent` was created to handle clean-up before navigating. You can use it instead of creating a new event class


<!-- Sent from Reviewable.io -->

2024-02-02 14:16 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010#-Npe-ktl2EJy-hZl6Ywz:-Npe6Nro66T3k7uvokSQ:b-txepsk) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/855a200659f031e8355b777cf8e97268dc848bee/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L58)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`NavigationRequestEvent` was created to handle clean-up before navigating. You can use it instead of creating a new event class
</blockquote></details>

Unfortunately I can't use `NavigationRequestEvent` in my case. At first, the views in Translation mode undock immediately when that event is fired, thus subscription to this event will be closed. Secondly, I'm using `BeforeNavigationEvent` not only when docking other views, but also when switching between chapters and steps.


<!-- Sent from Reviewable.io -->

2024-02-02 19:37 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010#-Npe-ktl2EJy-hZl6Ywz:-NpfJS1L5pAxTU0wbYXU:bve44ip) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/855a200659f031e8355b777cf8e97268dc848bee/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L58)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Unfortunately I can't use `NavigationRequestEvent` in my case. At first, the views in Translation mode undock immediately when that event is fired, thus subscription to this event will be closed. Secondly, I'm using `BeforeNavigationEvent` not only when docking other views, but also when switching between chapters and steps.
</blockquote></details>

Could we add a payload to the event for pre-navigation, which would in this case then carry the lambda to clean the images? So as to use the same NavigationEvent, but detach the execution of that method from the View which is docking status dependent?


<!-- Sent from Reviewable.io -->

2024-02-05 13:15 UTC, AnonymousWalker approved these changes

2024-02-05 15:59 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt` line 58 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1010#-Npe-ktl2EJy-hZl6Ywz:-Nptz0yc8y-CcYdcpjA8:bdr1vsn) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/855a200659f031e8355b777cf8e97268dc848bee/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/AppBar.kt#L58)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Could we add a payload to the event for pre-navigation, which would in this case then carry the lambda to clean the images? So as to use the same NavigationEvent, but detach the execution of that method from the View which is docking status dependent?
</blockquote></details>

@jsarabia, I'm not sure how to achieve this


<!-- Sent from Reviewable.io -->

2024-02-05 17:22 UTC, merged