Fix for incorrect teleprompter after restarting chapter (OT-819)
Bible-Translation-Tools/otter pull request #1022
Opened 2024-02-06 21:20 UTC by darrellcolehill

Modifies the list as a whole and not just elements in the list

2024-02-06 21:57 UTC, AnonymousWalker requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1022)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 500 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1022#-Nq-Q1x4ERH_A7x-CNfo:-Nq-Q1x56kD8RMNd_2Oo:b-z3miwd) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/44b3418d878d26b3a620f7039d89d6bd1b37d9d7/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L500)):*
> ```Kotlin
>         }
>         narratableList[0].state = TeleprompterItemState.RECORD
>         narratableList.setAll(narratableList.map { it })
> ```

`.setAll(narratableList.toList()) ` would be more intentional


<!-- Sent from Reviewable.io -->

2024-02-07 15:39 UTC, darrellcolehill reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1022)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt` line 500 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1022#-Nq-Q1x4ERH_A7x-CNfo:-Nq3Cnxx3FN_UWMAG1tL:b-365lv3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/44b3418d878d26b3a620f7039d89d6bd1b37d9d7/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationViewModel.kt#L500)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

`.setAll(narratableList.toList()) ` would be more intentional
</blockquote></details>

I like that much better! It is much more readable. 


<!-- Sent from Reviewable.io -->

2024-02-07 16:12 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1022#-:-Nq3KnHGDf7XL-76vJub:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)



<!-- Sent from Reviewable.io -->

2024-02-07 17:25 UTC, AnonymousWalker approved these changes

2024-02-07 17:26 UTC, merged