Fix marker & waveform alignment (OT-848)
Bible-Translation-Tools/otter pull request #1071
Opened 2024-03-12 14:57 UTC by AnonymousWalker

2024-03-15 12:38 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt` line 45 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-Nt16PmJ1M6P934ZuFUf:-Nt16PmJ1M6P934ZuFUg:b-pkmp7b) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2ff7c9faa146a65d10f2d20d72f014858e10ce3f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt#L45)):*
> ```Kotlin
>     framesOnScreen: Int = SECONDS_ON_SCREEN * SAMPLE_RATE
> ): Int {
>     val framesInPixel = framesOnScreen / width
> ```

Why are you flooring this BEFORE multiplying by the number of pixels?


<!-- Sent from Reviewable.io -->

2024-03-15 14:25 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt` line 45 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-Nt16PmJ1M6P934ZuFUf:-Nt1UGyiDECbHDqk_Bnq:bww9co) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2ff7c9faa146a65d10f2d20d72f014858e10ce3f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why are you flooring this BEFORE multiplying by the number of pixels?
</blockquote></details>

since I made this consistent with how the waveform width is computed (computeImageWidth). `pixelsToFrames`and `framesToPixels` function is used by the markers whereas `computeImageWidth` is used by the waveform.

If any of these is computed differently than the other, we will run into the issue of misalignment between markers and waveform


<!-- Sent from Reviewable.io -->

2024-03-15 18:16 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt` line 45 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-Nt16PmJ1M6P934ZuFUf:-Nt2Jyeq4CSKe3v1_qVT:b-7fbi3i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2ff7c9faa146a65d10f2d20d72f014858e10ce3f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt#L45)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

since I made this consistent with how the waveform width is computed (computeImageWidth). `pixelsToFrames`and `framesToPixels` function is used by the markers whereas `computeImageWidth` is used by the waveform.

If any of these is computed differently than the other, we will run into the issue of misalignment between markers and waveform
</blockquote></details>

that doesn't answer my question
Why are you doing integer division?


<!-- Sent from Reviewable.io -->

2024-03-15 18:17 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt` line 45 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-Nt16PmJ1M6P934ZuFUf:-Nt2K51rDK3PEW4zkCBR:bngbpxe) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2ff7c9faa146a65d10f2d20d72f014858e10ce3f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

that doesn't answer my question
Why are you doing integer division?
</blockquote></details>

In terms of consistency, neither of them were doing integer division before- I want an explanation as to why integer division is the correct solution here


<!-- Sent from Reviewable.io -->

2024-03-15 18:31 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[`jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt` line 45 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-Nt16PmJ1M6P934ZuFUf:-Nt2LS7Z0smVJ-5a6_8G:bmcirn5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2ff7c9faa146a65d10f2d20d72f014858e10ce3f/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/model/DisplayAndAudioPositionFormulas.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

In terms of consistency, neither of them were doing integer division before- I want an explanation as to why integer division is the correct solution here
</blockquote></details>

```
    fun computeImageWidth(width: Int, secondsOnScreen: Int = SECONDS_ON_SCREEN): Double {
        ...
        val samplesPerPixel = samplesPerScreenWidth / width
        ...
    }

```
```
fun framesToPixels(
    frames: Int,
    width: Int = Screen.getMainScreen().platformWidth,
    framesOnScreen: Int = SECONDS_ON_SCREEN * SAMPLE_RATE
): Int {
    val framesInPixel = framesOnScreen / width
    ...
}
```

Here's the consistency that I meant. If samplesPerPixel (framesInPixel) was of type Double in the latter, we ran back to the problem with OT-770 which @mXaln attempted to fix with #909. Because `samplesPerPixel: Int` was used for rendering the waveform, the markers also need to do the same.


<!-- Sent from Reviewable.io -->

2024-03-18 12:36 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1071#-:-NtGZ-I84_s1875_BNbH:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @mXaln)



<!-- Sent from Reviewable.io -->

2024-03-18 12:49 UTC, merged