Preload GL sources when initializing app
Bible-Translation-Tools/otter pull request #1078
Opened 2024-03-20 16:48 UTC by AnonymousWalker

2024-03-22 17:56 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1078)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`assets/build.gradle` line 96 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1078#-NtbHxT-1kLmnrmxwa1L:-NtbHxT-1kLmnrmxwa1M:b-bg1p9t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1cd6daefc73e97eef2bd545de39b893ee4bdadb0/assets/build.gradle#L96)):*
> ```Gradle
>                 filename.replaceAll('-\\.json$', '.json')
>             } else {
>                 filename.replaceAll('-V21-05\\.zip\$', '.zip')
> ```

why did you replace the wildcard? what if the version changes?


<!-- Sent from Reviewable.io -->

2024-03-22 18:23 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1078)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`assets/build.gradle` line 96 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1078#-NtbHxT-1kLmnrmxwa1L:-NtbNPsK-TgfmuGzCqyu:b-ls9aso) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1cd6daefc73e97eef2bd545de39b893ee4bdadb0/assets/build.gradle#L96)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why did you replace the wildcard? what if the version changes?
</blockquote></details>

I removed it for two reasons:
1. If we there is a newer version of the resource or we want to adhere to a specific version, we must update the URL of such resource in the `gl_sources.json`file. For en_ulb we are targeting `V21-05` which the URL is pointing to that source instead of master.
2. There are languages that contains a dash "-" character in its name, e.g. `es-419_ulb`, which caused a problem when accessing.


<!-- Sent from Reviewable.io -->

2024-03-22 18:25 UTC, AnonymousWalker commented on assets/src/main/resources/gl_sources.json
> +    "url":"https://content.bibletranslationtools.org/WA-Catalog/en_ulb/archive/V21-05.zip"
we moved `content 'wa-catalog:en_ulb:V21-05@zip'` here

2024-03-22 18:29 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1078#-:-NtbQI_IDSZtat6nn0Qv:bnfp4nl)* status: 0 of 6 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-03-25 18:47 UTC, AnonymousWalker commented
#1081

2024-03-25 18:47 UTC, closed without merging