Use slug when title empty
Bible-Translation-Tools/otter pull request #1159
Opened 2024-07-08 18:46 UTC by darrellcolehill

Uses slug when title is empty in Narration and for export dialog.

2024-07-08 19:23 UTC, AnonymousWalker requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 146 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1159#-O1In1oi2s-6b8vTQ0xu:-O1In1oi2s-6b8vTQ0xv:bac35ss) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3a3d03f2bab48785257e51744ccc9d1d092e4762/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L146)):*
> ```Kotlin
>         it?.let {
>             val title = it.target.title.takeIf { bookTitle -> bookTitle.isNotEmpty() }
>                 ?: it.target.slug.replaceFirstChar { firstChar -> firstChar.uppercaseChar() }
> ```

I'd use uppercase for the slugs


<!-- Sent from Reviewable.io -->

2024-07-08 19:28 UTC, darrellcolehill reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1159)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt` line 146 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1159#-O1In1oi2s-6b8vTQ0xu:-O1IoLMJ42RZ8gTENm-B:b-hfghm4) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/3a3d03f2bab48785257e51744ccc9d1d092e4762/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationHeader.kt#L146)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I'd use uppercase for the slugs
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2024-07-08 19:50 UTC, AnonymousWalker approved these changes

2024-07-12 12:20 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/1159#-:-O1ask1oCgCzb7mGPslb:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)



<!-- Sent from Reviewable.io -->

2024-07-12 12:20 UTC, merged