Generate verse markers on compiling a chapter
Bible-Translation-Tools/otter pull request #467
Opened 2021-12-21 19:50 UTC by AnonymousWalker

Generate markers when compiling a chapter from verses. Each marker placed at the beginning of each verse take

2021-12-22 14:22 UTC, mXaln approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2021-12-28 18:28 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt, line 59 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/467#-Ms1HvO6DjG7aF-_NP4E:-Ms1HvO6DjG7aF-_NP4F:b-63ridn) ([raw file](https://github.com/bible-translation-tools/orature/blob/528c0ad31bd53e97aafb5497ac79f5c535d5c592/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt#L59)):*
> ```Kotlin
>                     )
>                     markerLocation += audioFile.totalFrames
>                     markerId++
> ```

You can't rely on the assumption that verse numbers are sequential. This is incorrect for verse bridges and chunks.

You need to add the starting marker in each of the verse by verse recordings, then in this usecase, read the marker metadata and use the label from the file.


<!-- Sent from Reviewable.io -->

2021-12-28 18:28 UTC, jsarabia reviewed
When you've made the correction, please also add unit tests.

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467#-:-Ms1IIaLCAhMXFWV-Hvn:bmisypv)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)



<!-- Sent from Reviewable.io -->

2021-12-30 16:28 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/LabeledAudio.kt, line 23 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/467#-MsB9GNS9Y3OZawKcfIj:-MsB9GNS9Y3OZawKcfIk:b3gil5l) ([raw file](https://github.com/bible-translation-tools/orature/blob/1327ec11fa6de0cf944e8c6a2305087886e6812f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/LabeledAudio.kt#L23)):*
> ```Kotlin
> import java.io.File
> 
> data class LabeledAudio(val title: String, val file: File)
> ```

I don't want an entire new class just to solve one problem. Otherwise we end up never using the same class for anything, never knowing what something is or why, because everything takes its own slight modification of the same thing.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt, line 64 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/467#-MsB9dyO9dzfjnzNTJ_V:-MsB9dyO9dzfjnzNTJ_W:b-dk82nl) ([raw file](https://github.com/bible-translation-tools/orature/blob/1327ec11fa6de0cf944e8c6a2305087886e6812f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt#L64)):*
> ```Kotlin
> 
>                 audioList.forEach { audio ->
>                     val audioFile = AudioFile(audio.file)
> ```

If you have an audio file, you can get its metadata. If you can get its metadata, you can get its list of verses. Use those, not "audio.title"

Place the start marker automatically at the beginning of verse files when they're created, and then the solution here is easy.


<!-- Sent from Reviewable.io -->

2022-01-05 17:36 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt, line 64 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/467#-MsB9dyO9dzfjnzNTJ_V:-MsfJ4bg3XFm2BBm6Sw4:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/1327ec11fa6de0cf944e8c6a2305087886e6812f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/content/ConcatenateAudio.kt#L64)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

If you have an audio file, you can get its metadata. If you can get its metadata, you can get its list of verses. Use those, not "audio.title"

Place the start marker automatically at the beginning of verse files when they're created, and then the solution here is easy.
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/LabeledAudio.kt, line 23 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/467#-MsB9GNS9Y3OZawKcfIj:-MsfJ5VA-6zMed1mOrar:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/1327ec11fa6de0cf944e8c6a2305087886e6812f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/audio/LabeledAudio.kt#L23)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't want an entire new class just to solve one problem. Otherwise we end up never using the same class for anything, never knowing what something is or why, because everything takes its own slight modification of the same thing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 17:51 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/ChapterPageViewModel.kt
> +
adapt with existing takes which have not previously contained marker in metadata

2022-01-05 19:20 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/467#-:-MsffmgU7oVlAakoaquy:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)



<!-- Sent from Reviewable.io -->

2022-01-05 19:20 UTC, merged