Fix import export
Bible-Translation-Tools/otter pull request #514
Opened 2022-03-08 17:00 UTC by AnonymousWalker

Sync version with source before actually importing project

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bible-translation-tools/orature/514)

2022-03-09 13:44 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/514)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt, line 125 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/514#-MxiuXiyE6kHpS_2rf3M:-MxiuXiyE6kHpS_2rf3N:b-n48r4e) ([raw file](https://github.com/bible-translation-tools/orature/blob/d16ce44ab15042632dfbc0012ce0cf14f77b309f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt#L125)):*
> ```Kotlin
>                     }
>                     // apply source version to target version to synchronize before import
>                     manifest.dublinCore.version = sourceCollection.resourceContainer!!.version
> ```

Move this version update block to a function
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt, line 151 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/514#-Mxiummx-8vLCzuuN71j:-Mxiummx-8vLCzuuN71k:b-yq65jy) ([raw file](https://github.com/bible-translation-tools/orature/blob/d16ce44ab15042632dfbc0012ce0cf14f77b309f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt#L151)):*
> ```Kotlin
>         metadata: ResourceMetadata,
>         manifestProject: Project,
>         sourceCollection: Collection
> ```

Why are you moving from a set to a single collection?


<!-- Sent from Reviewable.io -->

2022-03-09 16:21 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/514)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt, line 125 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/514#-MxiuXiyE6kHpS_2rf3M:-MxjTuUJ4tAO0U1mcIet:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/d16ce44ab15042632dfbc0012ce0cf14f77b309f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt#L125)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Move this version update block to a function
</blockquote></details>

Done.
___
*[common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt, line 151 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/514#-Mxiummx-8vLCzuuN71j:-Mxj9fWcAMaFQpzMUVa9:bndnhl9) ([raw file](https://github.com/bible-translation-tools/orature/blob/d16ce44ab15042632dfbc0012ce0cf14f77b309f/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt#L151)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why are you moving from a set to a single collection?
</blockquote></details>

I was basically moving the whole block which finds a single source to the method above


<!-- Sent from Reviewable.io -->

2022-03-14 19:27 UTC, AnonymousWalker commented on common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt
> -
this block was moved to the method above ^ so that the project metadata can be constructed with appropriate version, before passing into this method

2022-03-14 19:27 UTC, AnonymousWalker commented on common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/ProjectImporter.kt
> -
this block was moved to the method above ^ so that the project metadata can be constructed with appropriate version, before passing into this method

2022-03-15 20:51 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/514#-:-MyELHBS8IMfdzA-POhE:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2022-03-15 20:53 UTC, merged