Prevent unselect plugin
Bible-Translation-Tools/otter pull request #529
Opened 2022-03-23 19:05 UTC by AnonymousWalker

2022-03-24 12:19 UTC, mXaln requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 264 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Myvq8PN7iT1Qrs5su4G:-Myvq8PN7iT1Qrs5su4H:b-sgglta) ([raw file](https://github.com/bible-translation-tools/orature/blob/e4d3aa3d725c5ddcec89a854638641ff05727041/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L264)):*
> ```Kotlin
>                                         setOnAction {
>                                             if (isSelected) {
>                                                 viewModel.selectRecorder(pluginData)
> ```

Should be selectEditor here



_Code quote:_
```Kotlin
                                        selectedProperty().onChange { selected ->
                                            if (selected) viewModel.selectRecorder(pluginData)
```


<!-- Sent from Reviewable.io -->

2022-03-24 12:25 UTC, mXaln commented
@AnonymousWalker It deselects if you use keyboard keys

2022-03-25 10:18 UTC, mXaln requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 259 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Mz-LZ7R0kvqTP6GBCTw:-Mz-LZ7R0kvqTP6GBCTx:bere2lh) ([raw file](https://github.com/bible-translation-tools/orature/blob/400c2deccfaee58376e889fef98708ee1ade368c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L259)):*
1. By using the radio button instead of our SelectButton, you are discarding of the design that we need. You can find the SelectButton in BookWizard's filter menu, it works fine there. Select Button has also optional text, which radio button doesn't have. So I recommend to use it.

![vlcsnap-2022-03-25-05h24m25s888.png](https://files.reviewableusercontent.io/images/reviewable/3640469/Sz1FuFfXKM-rjJv_0_m6D0sY/vlcsnap-2022-03-25-05h24m25s888.png)

2. I got instructions from Thomas about select buttons: 
> ARROW keys should never auto select any radio buttons, but can be used to highlight them

So you can change its behavior from ToggleButtonBehavior to ButtonBehavior.

3. You only need to make the SelectButton not deselectable. And I would recommend to do that in the button itself if possible, not in the SettingsView.
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 262 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Mz-_1yV6RqHivxigHA-:-Mz-_1yV6RqHivxigHA0:bpc1yel) ([raw file](https://github.com/bible-translation-tools/orature/blob/400c2deccfaee58376e889fef98708ee1ade368c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L262)):*
> ```Kotlin
>                                         addClass("wa-radio")
>                                         isDisable = !pluginData.canRecord
>                                         if (pluginData.canRecord) {
> ```

There is no need to do this here. ToggleGroup won't select disabled select anyway.


<!-- Sent from Reviewable.io -->

2022-03-25 13:22 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 259 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Mz-LZ7R0kvqTP6GBCTw:-Mz0Ec7zEBcNKTFZyVtO:b-opqpao) ([raw file](https://github.com/bible-translation-tools/orature/blob/400c2deccfaee58376e889fef98708ee1ade368c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L259)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

1. By using the radio button instead of our SelectButton, you are discarding of the design that we need. You can find the SelectButton in BookWizard's filter menu, it works fine there. Select Button has also optional text, which radio button doesn't have. So I recommend to use it.

![vlcsnap-2022-03-25-05h24m25s888.png](https://files.reviewableusercontent.io/images/reviewable/3640469/Sz1FuFfXKM-rjJv_0_m6D0sY/vlcsnap-2022-03-25-05h24m25s888.png)

2. I got instructions from Thomas about select buttons: 
> ARROW keys should never auto select any radio buttons, but can be used to highlight them

So you can change its behavior from ToggleButtonBehavior to ButtonBehavior.

3. You only need to make the SelectButton not deselectable. And I would recommend to do that in the button itself if possible, not in the SettingsView.
</blockquote></details>

Thank you very much, I was having a hard time trying different ways. Looked like I found the working solution from your thought
___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 262 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Mz-_1yV6RqHivxigHA-:-Mz0EbaE1sg_9UuY7dLB:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/400c2deccfaee58376e889fef98708ee1ade368c/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L262)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

There is no need to do this here. ToggleGroup won't select disabled select anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-25 13:23 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt, line 264 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/529#-Myvq8PN7iT1Qrs5su4G:-Mz0EhD96VfAg2ZorcBF:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/e4d3aa3d725c5ddcec89a854638641ff05727041/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/drawer/SettingsView.kt#L264)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Should be selectEditor here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-25 14:26 UTC, mXaln approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2022-03-25 15:22 UTC, mXaln approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2022-03-29 08:27 UTC, merged