Allow removing translation
Bible-Translation-Tools/otter pull request #535
Opened 2022-03-29 19:52 UTC by AnonymousWalker

This PR enables the ability to remove a translation (with 0 derived project from it).
Also, the 'create project' button is placed on top of the book cards.

2022-03-30 14:01 UTC, mXaln requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/535)* status: all files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt, line 126 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/535#-MzQ65ca0tUIQT8fzT0f:-MzQ65ca0tUIQT8fzT0g:bm9r034) ([raw file](https://github.com/bible-translation-tools/orature/blob/51da3ef68667a76b55ae97b5d00430b534b30054/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt#L126)):*
> ```Kotlin
>                             orientationScaleProperty.bind(settingsViewModel.orientationScaleProperty)
> 
>                             onRemoveTranslation = {
> ```

IMHO I would do the action as a property with setOn method for convenience and similar code design. Like it's done with setOnNewBookAction method.


<!-- Sent from Reviewable.io -->

2022-03-30 15:13 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/535)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)

___
*[jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt, line 126 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/535#-MzQ65ca0tUIQT8fzT0f:-MzQNpO012GbgIc5szHW:b-773sqb) ([raw file](https://github.com/bible-translation-tools/orature/blob/51da3ef68667a76b55ae97b5d00430b534b30054/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/HomePage.kt#L126)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

IMHO I would do the action as a property with setOn method for convenience and similar code design. Like it's done with setOnNewBookAction method.
</blockquote></details>

yeah that's fine, too.


<!-- Sent from Reviewable.io -->

2022-03-30 15:16 UTC, mXaln requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/535)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard.kt, line 48 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/535#-MzQOTTzAVqcbWugSX1r:-MzQOTTzAVqcbWugSX1s:b-yevggm) ([raw file](https://github.com/bible-translation-tools/orature/blob/b5ab0281b8c3267ac4a41aa4724917819b027ded/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard.kt#L48)):*
> ```Kotlin
>     val orientationScaleProperty = SimpleDoubleProperty()
> 
>     val onRemoveTranslation = SimpleObjectProperty<() -> Unit>()
> ```

Could you add Property to the name? onRemoveTranslationProperty


<!-- Sent from Reviewable.io -->

2022-03-30 15:18 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/535)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard.kt, line 48 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/535#-MzQOTTzAVqcbWugSX1r:-MzQP7OD2hNwwqlwSZON:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/b5ab0281b8c3267ac4a41aa4724917819b027ded/jvm/controls/src/main/kotlin/org/wycliffeassociates/otter/jvm/controls/card/TranslationCard.kt#L48)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Could you add Property to the name? onRemoveTranslationProperty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-30 15:19 UTC, mXaln approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/535)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia and @mXaln)



<!-- Sent from Reviewable.io -->

2022-04-01 18:21 UTC, merged

2022-05-31 14:40 UTC, OpThomasPrime1 commented
Verified by QA (Thomas Oliver)