Override combobox accessability
Bible-Translation-Tools/otter pull request #537
Opened 2022-03-30 15:53 UTC by mXaln

2022-03-31 13:21 UTC, AnonymousWalker commented on jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt
> +
should we call consume() once after capture/filtering the event? Maybe at line 93 and 113

2022-03-31 13:31 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/537)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt, line 93 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/537#-MzQX0_orZVcLaKgR_iZ-r1-93:-MzV9kl2BGN13q9nDOSW:b3kk4js) ([raw file](https://github.com/bible-translation-tools/orature/blob/53fffe3977f7f232866819ce22dfae210ea59f49/jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt#L93)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

should we call consume() just once after capture/filtering the event? Maybe at line 93 and 113
</blockquote></details>

Sorry, the line numbers that you specified are different in my editor, for some reason. If you mean to consume all events, then we don't want this. We want to consume only specific key events and let others pass through.


<!-- Sent from Reviewable.io -->

2022-03-31 13:32 UTC, AnonymousWalker requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/537)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt, line 73 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/537#-MzV9_fMD_heSOmkF7wG:-MzV9_fMD_heSOmkF7wH:b8fyqvb) ([raw file](https://github.com/bible-translation-tools/orature/blob/53fffe3977f7f232866819ce22dfae210ea59f49/jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt#L73)):*
> ```Kotlin
>  * @param action Action to invoke when value has changed
>  */
> fun <T> ComboBox<T>.overrideEventsAndRun(action: (T) -> Unit = {}) {
> ```

looks like this method capture the keyboard events, could you name it something more specific? ` overrideEvents ` sounds like overriding ALL event this node could potentially emit


<!-- Sent from Reviewable.io -->

2022-03-31 13:38 UTC, AnonymousWalker commented
*[jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt, line 93 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/537#-MzQX0_orZVcLaKgR_iZ-r1-93:-MzVBgalEdP3fThaeul1:b-kett6w) ([raw file](https://github.com/bible-translation-tools/orature/blob/53fffe3977f7f232866819ce22dfae210ea59f49/jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt#L93)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Sorry, the line numbers that you specified are different in my editor, for some reason. If you mean to consume all events, then we don't want this. We want to consume only specific key events and let others pass through.
</blockquote></details>

thanks for clarifying!


<!-- Sent from Reviewable.io -->

2022-03-31 13:44 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/537)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt, line 73 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/537#-MzV9_fMD_heSOmkF7wG:-MzVCvQS9H7zLMZHwBRT:b-fv3ngl) ([raw file](https://github.com/bible-translation-tools/orature/blob/53fffe3977f7f232866819ce22dfae210ea59f49/jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt#L73)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

looks like this method capture the keyboard events, could you name it something more specific? ` overrideEvents ` sounds like overriding ALL event this node could potentially emit
</blockquote></details>

yeah, I was thinking of different names. And came up with this one. If you have a better idea, would be good.


<!-- Sent from Reviewable.io -->

2022-03-31 14:22 UTC, AnonymousWalker commented
*[jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt, line 73 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/537#-MzV9_fMD_heSOmkF7wG:-MzVLTPa7J7ze9PHOeEl:b-3a6se0) ([raw file](https://github.com/bible-translation-tools/orature/blob/53fffe3977f7f232866819ce22dfae210ea59f49/jvm/utils/src/main/kotlin/org/wycliffeassociates/otter/jvm/utils/NodeUtils.kt#L73)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

yeah, I was thinking of different names. And came up with this one. If you have a better idea, would be good.
</blockquote></details>

how about ` overrideDefaultKeyEvent() ` ?


<!-- Sent from Reviewable.io -->

2022-03-31 15:40 UTC, AnonymousWalker approved these changes

2022-04-01 18:21 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/537#-:-MzaMB2p7yQ-7auEw8De:bnfp4nl)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @mXaln)



<!-- Sent from Reviewable.io -->

2022-04-02 11:13 UTC, merged

2022-05-31 15:52 UTC, OpThomasPrime1 commented
Verified by QA (Thomas Oliver)