Verse marker app - Blocking controls: breadcrumbs, app settings, close
Bible-Translation-Tools/otter pull request #630
Opened 2022-07-13 19:11 UTC by AnonymousWalker

Previously, markerapp disables breadcrumb navigation and app bar when a plugin is opened (even for native plugins).

This PR releases the sandboxed controls for native plugins so that these controls are available after the waveform has finished loading. Additionally, navigating back or exit the app will automatically save the current data.

2022-07-13 19:12 UTC, AnonymousWalker commented
![image](https://user-images.githubusercontent.com/34975907/178813137-a161cd74-6875-4f17-be5c-10809480dadd.png)

2022-07-13 19:51 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/630)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 52 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t2w0o8WT5F6ktuZLF:-N6t2w0o8WT5F6ktuZLG:b8g324o) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L52)):*
> ```Kotlin
>     override fun onDock() {
>         super.onDock()
>         blockAppControlsWhenLoading()
> ```

Why should we block while it's loading?
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 160 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t3HuTA72bbeLUwedL:-N6t3HuTA72bbeLUwedM:b-v2pmgm) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L160)):*
> ```Kotlin
>                     }
>                 }
>             }
> ```

why do we need to make this change?
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 166 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t34t7EIRTzhpSoKD_:-N6t34t7EIRTzhpSoKDa:b6982f4) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L166)):*
> ```Kotlin
>         currentStage?.scene?.root
>             ?.let { node ->
>                 node.findChildren(BreadcrumbBar::class)?.firstOrNull()
> ```

The MarkerView should DEFINITELY not be aware of something like this, fire an event if this is absolutely necessary
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt` line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t51P13zi4Qo2pqmaO:-N6t51P13zi4Qo2pqmaP:bjs23lg) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt#L89)):*
> ```Kotlin
>                         System.gc()
>                     }
>                 }
> ```

saveAndQuit could still exist, but could call



_Suggestion:_
```Kotlin
saveChanges {
    (scope as ParameterizedScope).let {
        runLater {
            it.navigateBack()
            System.gc()
        }
    }
}                    
                    
```


<!-- Sent from Reviewable.io -->

2022-07-13 20:28 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/630)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 52 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t2w0o8WT5F6ktuZLF:-N6tEyImBDc-WzXWWWoz:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L52)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why should we block while it's loading?
</blockquote></details>

Done.
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 166 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t34t7EIRTzhpSoKD_:-N6tEwiiDInXTeo1p8t0:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L166)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

The MarkerView should DEFINITELY not be aware of something like this, fire an event if this is absolutely necessary
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 20:45 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/630)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @mXaln)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt` line 89 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t51P13zi4Qo2pqmaO:-N6tItX9077-jgpEqed-:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt#L89)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

saveAndQuit could still exist, but could call
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-15 13:13 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/630)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt` line 135 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N70xT-59lwnLiRPULsD:-N70xT-59lwnLiRPULsE:b9zsfbi) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt#L135)):*
> ```Kotlin
>     }
> 
>     fun save(callback: () -> Unit = {}) {
> ```

callback for what?
___
*[`jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt` line 136 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N70yWpb47Gab9fps-ST:-N70yWpb47Gab9fps-SU:b-ga5t8c) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/recorderapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/recorder/app/viewmodel/RecorderViewModel.kt#L136)):*
> ```Kotlin
> 
>     fun save(callback: () -> Unit = {}) {
>         logger.info("Closing Recorder...")
> ```

The recorder isn't exactly closing here like it definitively was before.
It's saving. Code could get refactored in which this function may be called without the intention of leaving the page.
You're welcome to log that it's saving, but log Closing Recorder above the line of code where it would actually be navigating away.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/AppContent.kt` line 44 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N70yBWd2Pwh_SgDkLYq:-N70yBWd2Pwh_SgDkLYr:beu9uth) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/screens/AppContent.kt#L44)):*
> ```Kotlin
>                 top = navigator.breadCrumbsBar.apply {
>                     orientationScaleProperty.bind(settingsViewModel.orientationScaleProperty)
>                     disableProperty().bind(rootViewModel.externalPluginOpenedProperty)
> ```

is disableWhen not more readable? This change to bind appears arbitrary (especially since disableWhen calls cleanBind)
___
*[`jvm/workbookplugin/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookplugin/plugin/ParameterizedScope.kt` line 27 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N70xgdCDFOzGBH5aA1Z:-N70xgdCDFOzGBH5aA1_:b-810he8) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/workbookplugin/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookplugin/plugin/ParameterizedScope.kt#L27)):*
> ```Kotlin
>     val parameters: Application.Parameters,
>     private val onNavigateBackCallback: () -> Unit,
>     private val onNavigateRequest: () -> Unit = {}
> ```

can you explain what this means?

How do I know what it does? When it should be called? What it should be doing?


<!-- Sent from Reviewable.io -->

2022-07-18 11:47 UTC, mXaln requested changes
> Reviewed 5 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/630)* status: all files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 150 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N7G2tWK1wOrSatP_JSU:-N7G2tWK1wOrSatP_JSV:b-f8mwjx) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L150)):*
> ```Kotlin
>             }
>             shortcut(Shortcut.ADD_MARKER.value, viewModel::placeMarker)
>             shortcut(Shortcut.GO_BACK.value) {
> ```

What was the reason to remove one-liner code?
___
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt` line 28 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N7G3AUO1wYGrsLzcauH:-N7G3AUO1wYGrsLzcauI:b-jae7jf) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/PlaybackControlsFragment.kt#L28)):*
> ```Kotlin
> import org.slf4j.LoggerFactory
> import org.wycliffeassociates.otter.jvm.markerapp.app.viewmodel.VerseMarkerViewModel
> import org.wycliffeassociates.otter.jvm.workbookplugin.plugin.ParameterizedScope
> ```

This is an unused import


<!-- Sent from Reviewable.io -->

2022-07-18 12:48 UTC, AnonymousWalker commented
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 150 at r4](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N7G2tWK1wOrSatP_JSU:-N7GLQcHEvUJkRWUnmQ3:bdcuqew) ([raw file](https://github.com/bible-translation-tools/orature/blob/fd1d3dbb4f4ac489befd73f8bb8de54dec5d04a4/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L150)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

What was the reason to remove one-liner code?
</blockquote></details>

thanks for the catch, I was adding a parameter and then removed it eventually without cleaning up this.


<!-- Sent from Reviewable.io -->

2022-07-18 12:49 UTC, AnonymousWalker commented
*[`jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt` line 160 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/630#-N6t3HuTA72bbeLUwedL:-N7GLfxj2dTs5Z9Man-e:b-nx2cuv) ([raw file](https://github.com/bible-translation-tools/orature/blob/ceeea277e06d98b6c958e527a01f1d873af3e3cb/jvm/markerapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/markerapp/app/view/MarkerView.kt#L160)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why do we need to make this change?
</blockquote></details>

yeah it was leftover that I forget to remove after changing the params


<!-- Sent from Reviewable.io -->

2022-07-19 14:44 UTC, closed without merging