OQuA Sprint 1
Bible-Translation-Tools/otter pull request #636
Opened 2022-07-27 14:52 UTC by Ro-Bert-Web

2022-07-27 15:22 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @Ro-Bert-Web)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt` line 29 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-DUAn-eqj4K9COJ-v:-N8-DUAn-eqj4K9COJ-w:bb7fod9) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/RcConstants.kt#L29)):*
> ```Kotlin
>     const val LICENSE_FILE = "LICENSE.md"
>     const val SOURCE_MEDIA_DIR = "media"
>     const val GRADES_FILE = "$APP_SPECIFIC_DIR/grades"
> ```

APP_SPECIFIC_DIR is orature, since you're piggy-backing off the Orature codebase.
This would put the tq evaluation under the orature directory, but we want this to be its own separate app, so it should be placed under an oqua directory.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterView.kt` line 13 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-DrZz0KE-MqzxE48t:-N8-DrZz0KE-MqzxE48u:b7uu1ws) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterView.kt#L13)):*
> ```Kotlin
>         super.onDock()
>         viewModel.dock()
>         println("Docked Chapter View")
> ```

don't include print statements in pull requests.

For cases where you do wish to log things, use the slf4j logger

private val logger = LoggerFactory.getLogger(ChapterView::class.java)
logger.info("log some info")


<!-- Sent from Reviewable.io -->

2022-07-27 17:08 UTC, AnonymousWalker requested changes
I'll have more to review, you can take a look at the current comments for now

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/HomeViewModel.kt
> +    fun undock() {}
if they are empty methods, you can delete them (therefore the callers, too)

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/NavBar.kt
> +            style { visibleWhen(viewModel.projectTitleProperty.isNotNull) }
you can try `visibleWhen()` without the `style { }` block

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/OQuAView.kt
> +        view.value?.onDock()
we should not manually call `onDock()` and `onUndock()`. They are part of the UI lifecycle which should be automatically handled.
For navigation, you could try this
```
val viewToDock = find<YourExpectedView>()
workspace.dock(viewToDock)
```

the "workspace" is a component of tornadofx within the current scope

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt
> +        gradeRepo = GradeRepository(directoryProvider, wbDataStore)
this could be replaced with dependency injection, similar to how the `IWorkbookRepository` (and other `IRepository...`) gets injected

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt
> +        gradeRepo.writeGradeFile(workbook, chapterNumber, questions)
This sounds more like save() instead of undock()

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt
> +data class GradeContent (
GradeContent makes me think of the details of a grading section or the grading components... but the member variables don't look like so. You may want to give it a better name

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt
> +fun gradeFromQuestion(question: Question): Grade {
here you could try some better alternatives:
1. using an extension method: `Grade.mapFromQuestion(...)`
2. adding a secondary constructor for Grade that takes in a Question object https://kotlinlang.org/docs/classes.html#secondary-constructors

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ProjectViewModel.kt
> +    val chaptersProperty = Bindings.createObjectBinding(
it'd be cleaner to declare `val chapters = observableListOf<Chapter>()` 
and then set the values for it in the `init {}` block

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ProjectView.kt
> +    override val root = listview<Chapter> {
how about `listview(viewModel.chapters) { ... }` ?

2022-07-27 17:08 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt
> +class GradeRepository (
this file should not contain the two data class above. They belong to their own separate file

2022-07-27 19:11 UTC, PurpleGuitar requested changes
> Reviewed 20 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 20 of 21 files reviewed, 19 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, @PurpleGuitar, and @Ro-Bert-Web)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt` line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-wGnw6ZaQEqI-5p12:-N8-wGnx84PyAFDTaOvz:b-6ymgg3) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt#L24)):*
> ```Kotlin
>             }
>         }
> //        right = vbox {
> ```

As a rule of thumb, don't commit commented-out code.  Please remove this dead code.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt` line 45 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-yDXt0TYdsiNgPXPU:-N8-yDXt0TYdsiNgPXPV:b99vwfr) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt#L45)):*
> ```Kotlin
>     }
> 
>     private fun updatePlayer() {
> ```

What does `updatePlayer()` do?   It's not clear from the title and there are no comments.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 59 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-zoys50FdcRrDbipd:-N8-zoyt97kdEtzw9yQs:b-mlkees) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L59)):*
> ```Kotlin
>             mapper.readValue<GradeContent>(file)
>         } catch (e: Exception) {
>             null
> ```

Generally, non-nullable fields are preferred to nullable fields if there's not a specific reason to use nulls.  Non-nullable fields are easier to understand and maintain.

I recommend changing this function to return a non-nullable GradeContent object and throw an IOException if not found.  Then handle the exception in `dock()` and `isFinished()`.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/NavBarViewModel.kt` line 26 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N800pma7QbU_fUcLpoN:-N800pma7QbU_fUcLpoO:b-kaltht) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/NavBarViewModel.kt#L26)):*
> ```Kotlin
> 
>     fun dock() {}
>     fun undock() {}
> ```

Are you overriding dock() and undock() with empty bodies intentionally?  It's better not to define them if you don't plan to override them.  I'm concerned that you might be eclipsing superclass behavior of the methods this way.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TCardListCellFragment.kt` line 22 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8034zk9yCNCUENcp9R:-N8034zk9yCNCUENcp9S:b-y60w5r) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TCardListCellFragment.kt#L22)):*
> ```Kotlin
>     )
>     private val questionsURLProperty = Bindings.createStringBinding(
>         { "https://content.bibletranslationtools.org/WA-Catalog/${itemProperty.value?.translation?.source?.slug}_tq" },
> ```

I like that you made this configurable.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TCardListCellFragment.kt` line 43 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N803DRW5DT-OmDzc3I9:-N803DRW5DT-OmDzc3IA:b-rofuxp) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TCardListCellFragment.kt#L43)):*
> ```Kotlin
>             text("You do not have the questions downloaded for this language")
>             hbox {
>                 text("You can find them at ")
> ```

Nice! :grinning: 
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TQListCellFragment.kt` line 40 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N803JfX4V67kaVvsMWs:-N803JfX4V67kaVvsMWt:b7nk1wg) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/TQListCellFragment.kt#L40)):*
> ```Kotlin
> 
>         vbox {
>             managedWhen(visibleProperty()) // Included for the possibility of hidding the answers initially
> ```

typo: hidding -> hiding


<!-- Sent from Reviewable.io -->

2022-07-28 12:34 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 20 of 21 files reviewed, 19 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, @PurpleGuitar, and @Ro-Bert-Web)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 10 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIe-r1-10:-N83lAuN8Yr934V03BcJ:b-1qsnxm) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L10)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

here you could try some better alternatives:
1. using an extension method: `Grade.mapFromQuestion(...)`
2. adding a secondary constructor for Grade that takes in a Question object https://kotlinlang.org/docs/classes.html#secondary-constructors
</blockquote></details>

An extension method wouldn't work here, you would need it to go in a companion object:
https://kotlinlang.org/docs/object-declarations.html#companion-objects

Companion objects are how Kotlin does static methods.

A secondary constructor is probably the better way to go.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 36 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIe-r1-36:-N83m04V-m9yOqI4QKO6:b-9zu97r) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L36)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this file should not contain the two data class above. They belong to their own separate file
</blockquote></details>

to clarify; it's okay to have multiple classes in a file in Kotlin (unlike Java), and if these were private especially it would be okay.

The issue here is that these are parts of different architectural layers that you would typically have in different packages, with the data classes belonging to your data/entity layer, and your repository belonging to your persistence layer.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 59 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-zoys50FdcRrDbipd:-N83mfwN91P2HMVicper:b-yfi592) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L59)):*
<details><summary><i>Previously, PurpleGuitar (Craig Oliver) wrote…</i></summary><blockquote>

Generally, non-nullable fields are preferred to nullable fields if there's not a specific reason to use nulls.  Non-nullable fields are easier to understand and maintain.

I recommend changing this function to return a non-nullable GradeContent object and throw an IOException if not found.  Then handle the exception in `dock()` and `isFinished()`.
</blockquote></details>

I'll also add that when doing try/catch, it's a better practice to catch the specific exceptions that are thrown and try to avoid just a general "catch Exception"


<!-- Sent from Reviewable.io -->

2022-07-28 13:23 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt
> +class ChapterListCellFragment: ListCellFragment<Chapter>() {
Nice use of ListCellFragment<> instead of ListCell

2022-07-28 13:23 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt
> +    private fun getQuestions(): MutableList<Question> {
may I know why we need a `MutableList` here?

2022-07-28 13:23 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/HomeViewModel.kt
> +    fun undock() {}
empty methods

2022-07-28 13:23 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/NavBarViewModel.kt
> +    fun undock() {}
empty methods

2022-07-28 13:23 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ProjectViewModel.kt
> +    fun undock() {}
empty methods

2022-07-28 18:56 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 3 of 24 files reviewed, 24 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, @PurpleGuitar, and @Ro-Bert-Web)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 359 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N858mKJ2NIPnP5wS6iL:-N858mKJ2NIPnP5wS6iM:b2x6oep) ([raw file](https://github.com/bible-translation-tools/orature/blob/b536afb3f2313bc3161c3a5a3e427edc6ae17421/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L359)):*
> ```Kotlin
>         file.extension.lowercase().let { it == "wav" || it == "mp3" }
> 
>     fun getResultsFile(): File {
> ```

is this a results file or a grades file?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterResults.kt` line 3 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N859_kH2MdNKQYuII9Q:-N859_kH2MdNKQYuII9R:bvalfbs) ([raw file](https://github.com/bible-translation-tools/orature/blob/b536afb3f2313bc3161c3a5a3e427edc6ae17421/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterResults.kt#L3)):*
> ```Kotlin
> package org.wycliffeassociates.otter.jvm.workbookapp.oqua
> 
> data class ChapterResults (
> ```

How about "ChapterDraftEvaluation"
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt` line 53 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N859JUFC0NJx4W6XPCE:-N859JUFC0NJx4W6XPCF:b-osa8hc) ([raw file](https://github.com/bible-translation-tools/orature/blob/b536afb3f2313bc3161c3a5a3e427edc6ae17421/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt#L53)):*
> ```Kotlin
>         result = 31 * result + (question?.hashCode() ?: 0)
>         result = 31 * result + (answer?.hashCode() ?: 0)
>         return result
> ```

Objects.hash(end, question, answer) will do this for you


<!-- Sent from Reviewable.io -->

2022-07-28 19:16 UTC, Ro-Bert-Web reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 3 of 24 files reviewed, 23 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @PurpleGuitar)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 359 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N858mKJ2NIPnP5wS6iL:-N85B7No1hGh50d5Ai1r:b-gd3327) ([raw file](https://github.com/bible-translation-tools/orature/blob/b536afb3f2313bc3161c3a5a3e427edc6ae17421/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L359)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

is this a results file or a grades file?
</blockquote></details>

I renamed grades to results for consistency. I missed the name in RcConstants.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt` line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIb-r1-8:-N85CFeB3zY_0a_Ke1O3:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt#L8)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

Nice use of ListCellFragment<> instead of ListCell 
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt` line 24 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-wGnw6ZaQEqI-5p12:-N85CHUc6tYRZfjO4v0C:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterListCellFragment.kt#L24)):*
<details><summary><i>Previously, PurpleGuitar (Craig Oliver) wrote…</i></summary><blockquote>

As a rule of thumb, don't commit commented-out code.  Please remove this dead code.
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterResults.kt` line 3 at r2](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N859_kH2MdNKQYuII9Q:-N85CI__Aq19A_KomWad:bxlki3i) ([raw file](https://github.com/bible-translation-tools/orature/blob/b536afb3f2313bc3161c3a5a3e427edc6ae17421/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterResults.kt#L3)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

How about "ChapterDraftEvaluation"
</blockquote></details>

I don't want to call it a "DraftEvaluation" with everything else labeled as a "Result"
Would "DraftEvaluation" be better to rename everything by?
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt` line 26 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHId-r1-26:-N85C_Yl4A1W_I7Vodb2:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt#L26)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

this could be replaced with dependency injection, similar to how the `IWorkbookRepository` (and other `IRepository...`) gets injected
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt` line 42 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHId-r1-42:-N85CaWW-QO7WwuGXoLj:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt#L42)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

This sounds more like save() instead of undock()
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt` line 45 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-yDXt0TYdsiNgPXPU:-N85CbjL5KfNBjHcJbFQ:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt#L45)):*
<details><summary><i>Previously, PurpleGuitar (Craig Oliver) wrote…</i></summary><blockquote>

What does `updatePlayer()` do?   It's not clear from the title and there are no comments.
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt` line 53 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHId-r1-53:-N85CclLBeX1aS_JmT4k:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/ChapterViewModel.kt#L53)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

may I know why we need a `MutableList` here?
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 10 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIe-r1-10:-N85Ci3s6Lq5KenHo3Uj:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L10)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

An extension method wouldn't work here, you would need it to go in a companion object:
https://kotlinlang.org/docs/object-declarations.html#companion-objects

Companion objects are how Kotlin does static methods.

A secondary constructor is probably the better way to go.
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 28 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIe-r1-28:-N85CgPb0S9d0ucjIHnY:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L28)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

GradeContent makes me think of the details of a grading section or the grading components... but the member variables don't look like so. You may want to give it a better name
</blockquote></details>

Done.
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt` line 36 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N8-8NfQoAg9VlZIBHIe-r1-36:-N85CjKJ5uOxGZYf-5Dd:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/9ea1c73bc07fd1647e36ad88bfef876c6a6001c5/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/GradeRepository.kt#L36)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

to clarify; it's okay to have multiple classes in a file in Kotlin (unlike Java), and if these were private especially it would be okay.

The issue here is that t [...]

2022-07-28 21:02 UTC, PurpleGuitar approved these changes
> Reviewed 12 of 21 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: all files reviewed, 23 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @PurpleGuitar)



<!-- Sent from Reviewable.io -->

2022-07-28 21:04 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: all files reviewed, 21 unresolved discussions (waiting on @AnonymousWalker, @PurpleGuitar, and @Ro-Bert-Web)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt` line 29 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N85b3nJD706-Ky1lqtM:-N85b3nJD706-Ky1lqtN:b7d1k2k) ([raw file](https://github.com/bible-translation-tools/orature/blob/599e45c39259cf9ef4e278fdf11d45a6a3e6713b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt#L29)):*
> ```Kotlin
>         get() = resources
>             ?.resources
>             ?.blockingFirst()
> ```

This will cause issues if translationNotes is also imported; you should filter out "tq" specifically rather than effectively hard code in an array index (same with below)


<!-- Sent from Reviewable.io -->

2022-07-29 13:43 UTC, AnonymousWalker approved these changes

2022-07-29 16:17 UTC, Ro-Bert-Web reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636)* status: 22 of 24 files reviewed, 21 unresolved discussions (waiting on @AnonymousWalker, @jsarabia, and @PurpleGuitar)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt` line 29 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/636#-N85b3nJD706-Ky1lqtM:-N89jn4D4KXuCWnenyu8:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/599e45c39259cf9ef4e278fdf11d45a6a3e6713b/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/oqua/Question.kt#L29)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This will cause issues if translationNotes is also imported; you should filter out "tq" specifically rather than effectively hard code in an array index (same with below)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 18:32 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/636#-:-N8ADse-EiX-ZFITDRzv:bnfp4nl)* status: 22 of 24 files reviewed, 20 unresolved discussions (waiting on @AnonymousWalker and @PurpleGuitar)



<!-- Sent from Reviewable.io -->

2022-08-02 12:37 UTC, closed without merging