Import sources before projects - initializer
Bible-Translation-Tools/otter pull request #661
Opened 2022-08-24 19:40 UTC by AnonymousWalker

To avoids missing sources import after database creation/migration, we try importing all the resource containers in the internal directory (rc/src) before importing projects

2022-08-25 12:10 UTC, jsarabia requested changes
What kinds of things did you do to verify this code works?

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661#-:-NAJuKVX1w5ncfgeujxt:b-w2aajr)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt` line 173 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAJtOUyAUaXs9I12Ygj:-NAJtOUyAUaXs9I12Ygk:b-cerbkh) ([raw file](https://github.com/bible-translation-tools/orature/blob/dba720cbcfdef21f329b6254c11a305cd361c457/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt#L173)):*
> ```Kotlin
>         if (dir.isFile || !dir.exists()) return
> 
>         dir.walk().filter { it.isFile && it.name != EN_ULB_FILENAME }.forEach {
> ```

why are you excluding the en_ulb?
All of these could already be imported anyway. Why make this exception?
You could also check if a dublin core entry exists with the path of all these before trying an import.


<!-- Sent from Reviewable.io -->

2022-08-25 13:18 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt` line 173 at r1](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAJtOUyAUaXs9I12Ygj:-NAK8mycA8_kEip1jg-r:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/dba720cbcfdef21f329b6254c11a305cd361c457/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt#L173)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why are you excluding the en_ulb?
All of these could already be imported anyway. Why make this exception?
You could also check if a dublin core entry exists with the path of all these before trying an import.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 15:37 UTC, AnonymousWalker reviewed
I added the test

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661#-:-NAKdXVh2JihOdltlKzG:b-gs46kj)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2022-08-28 20:47 UTC, jsarabia requested changes
> Reviewed 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt` line 48 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAa9wQC8Pokpe4wal0T:-NAa9wQC8Pokpe4wal0U:b-ylpi4d) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt#L48)):*
> ```Kotlin
> ) : Installable {
>     override val name = "PROJECTS"
>     override val version = 2
> ```

why are we increasing the version number here but there is no migration from version 1 to 2?
___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeSources.kt` line 45 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAaAL8E3fcxJsHTKx5_:-NAaAL8F-6e1EB7YL5pz:b-ucl30u) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeSources.kt#L45)):*
> ```Kotlin
>     private fun importSources(dir: File) {
>         if (dir.isFile || !dir.exists()) return
>         val existingPaths = fetchSourcePaths()
> ```

it would probably be good to separate the guard statement from the rest of the function with an empty line
___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeUlb.kt` line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAaB7IMAw1tmb--sGPo:-NAaB7IMAw1tmb--sGPp:bpa5tnw) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeUlb.kt#L82)):*
> ```Kotlin
>     private fun isAlreadyImported(): Boolean {
>         val enUlbStream = javaClass.classLoader.getResourceAsStream(EN_ULB_PATH)!!
>         val tempFile = kotlin.io.path.createTempFile().toFile()
> ```

use the temp dir from the directory provider; we should NEVER use kotlin's createTempFile function.

if there's an io exception, the temp file won't get cleaned up (especially since you're not doing a delete call in try/finally. Delete on exit does NOT get called if an exception causes process termination) and we'll never know where to find it later. With the Orature temp dir, we're at least deleting that on app startup every time (and it gets deleted on uninstall).


<!-- Sent from Reviewable.io -->

2022-08-29 12:47 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661)* status: 1 of 12 files reviewed, 3 unresolved discussions (waiting on @jsarabia)

___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt` line 48 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAa9wQC8Pokpe4wal0T:-NAdaT6PAPZ9mfp6_SDu:b-lfxhz1) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeProjects.kt#L48)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

why are we increasing the version number here but there is no migration from version 1 to 2?
</blockquote></details>

nice catch. I previously added the changes and eventually moved them away
___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeSources.kt` line 45 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAaAL8E3fcxJsHTKx5_:-NAdd2mRCZVZYGu4Du3A:b-896fix) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeSources.kt#L45)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

it would probably be good to separate the guard statement from the rest of the function with an empty line
</blockquote></details>

Done.
___
*[`assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeUlb.kt` line 82 at r3](https://reviewable.io/reviews/bible-translation-tools/orature/661#-NAaB7IMAw1tmb--sGPo:-NAdcOHZ9q36DF2lHx1L:b-84pgrw) ([raw file](https://github.com/bible-translation-tools/orature/blob/44e6618e8c1945b244de4911c4490232695a3f1e/assets/src/main/kotlin/org/wycliffeassociates/otter/assets/initialization/InitializeUlb.kt#L82)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

use the temp dir from the directory provider; we should NEVER use kotlin's createTempFile function.

if there's an io exception, the temp file won't get cleaned up (especially since you're not doing a delete call in try/finally. Delete on exit does NOT get called if an exception causes process termination) and we'll never know where to find it later. With the Orature temp dir, we're at least deleting that on app startup every time (and it gets deleted on uninstall).
</blockquote></details>

Thanks for the suggestion, I replaced it


<!-- Sent from Reviewable.io -->

2022-08-29 14:21 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/orature/661#-:-NAdyfBQ43b4LICN8EpJ:bnfp4nl)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2022-08-29 14:21 UTC, merged