Preallocate projects
Bible-Translation-Tools/otter pull request #724
Opened 2023-03-19 22:06 UTC by jsarabia

Preallocates books from versification if they are not currently included in the source RC

The data (titles, sort, text) will be updated when an RC is updated that contains the uploaded books.

2023-03-20 17:34 UTC, AnonymousWalker requested changes
We need to update the test case for `mergeText()`. Also, could you add breaks to the extra-long lines in this PR?

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724#-:-NR-4EQP0TRcwROCdgah:b-37y3nf)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/MergeTextContent.kt` line 94 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724#-NR-2iG76l-nJWIfbWxq:-NR-2iG76l-nJWIfbWxr:bh2ik76) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/394b38caa9f2d3841740bb045b3e6183159ce200/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/MergeTextContent.kt#L94)):*
> ```Kotlin
>     private fun manifestFilePermutations(fromRc: ResourceContainer, project: Project): Map<String, InputStream> {
>         // TODO: get input streams of all files under a project directory for non-bundle RCs
>         //val content = fromRc.getProjectContent(project.identifier, fromRc.manifest.dublinCore.format)
> ```

should this be removed?


<!-- Sent from Reviewable.io -->

2023-03-27 12:42 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/MergeTextContent.kt` line 94 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724#-NR-2iG76l-nJWIfbWxq:-NRY4fBgEYAOGvrmadFL:b-nr3pgn) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/394b38caa9f2d3841740bb045b3e6183159ce200/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/projectimportexport/MergeTextContent.kt#L94)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

should this be removed?
</blockquote></details>

This is functionality that needs to be added from an RC lib, kind of bookmarking it to be here if we ever choose to add support for non-Bundle rcs


<!-- Sent from Reviewable.io -->

2023-03-27 13:59 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724)* status: 0 of 16 files reviewed, all discussions resolved

___
*[`jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/importer/TestExistingSourceImporter.kt` line 174 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/724#-NRYKUNbADUQmuXIt_gh:-NRYKUNbADUQmuXIt_gi:bcznhco) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/59204f281883775513d2896ef6875d8a7768263d/jvm/workbookapp/src/integration-test/kotlin/integrationtest/projects/importer/TestExistingSourceImporter.kt#L174)):*
> ```Kotlin
> 
>     @Test
>     fun `test text is updated in database when version is different`() {
> ```

Thanks for adding the test. However, I'm concerned with the length of this test function as there is mostly setup code -  this makes it hard to find where and what are actually tested.

I approved this PR so you can merge in afterwards.


<!-- Sent from Reviewable.io -->

2023-03-27 13:59 UTC, AnonymousWalker approved these changes

2023-03-27 19:44 UTC, merged