Fix unselected chunk takes when import project
Bible-Translation-Tools/otter pull request #725
Opened 2023-03-23 18:18 UTC by AnonymousWalker

Previously, after updating the content entity in the database, the collection's active connection was not updated with the new changes and thus it got out of sync. This PR applies the changes to the connection which takes effect when the workbook is reloaded

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725)

2023-03-23 18:19 UTC, AnonymousWalker commented on jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/viewmodel/AddFilesViewModel.kt
> +                return Single.just(ImportOptions(parameter.options))
temporary default values: import all

2023-03-31 17:42 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ContentRepository.kt` line 213 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725#-NRskifGCD5IS86qraEP:-NRskifGCD5IS86qraEQ:b7wk72u) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b021bfc88ed1fbf8f0b3479d1958cd244834a8af/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ContentRepository.kt#L213)):*
> ```Kotlin
>                 contentDao.update(entity)
> 
>                 activeConnections.keys.find { it.id == entity.collectionFk }?.let { collection ->
> ```

can you move this to a private function called something like updateContentInActiveConnection?

It would help with readability, as well as refactoring if the implementation for active connections changes.


<!-- Sent from Reviewable.io -->

2023-03-31 18:09 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ContentRepository.kt` line 213 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725#-NRskifGCD5IS86qraEP:-NRsqvfvAB8k5Sb8-7cy:b-4w8q7g) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/b021bfc88ed1fbf8f0b3479d1958cd244834a8af/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/ContentRepository.kt#L213)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can you move this to a private function called something like updateContentInActiveConnection?

It would help with readability, as well as refactoring if the implementation for active connections changes.
</blockquote></details>

good catch! Resolved


<!-- Sent from Reviewable.io -->

2023-03-31 19:38 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/725#-:-NRtAQ8s1zccAvwLjV1M:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-03-31 19:38 UTC, merged