Created Narration class
Bible-Translation-Tools/otter pull request #775
Opened 2023-07-12 12:13 UTC by mXaln

2023-07-13 19:38 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 644 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FkjRsAafIrUYeIIHj:-N_FkjRsAafIrUYeIIHk:b-yjb8oc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L644)):*
> ```Kotlin
>     }
> 
>     fun getProjectChapterAudioDir(workbook: Workbook, chapter: Chapter): File {
> ```

could we place this method in `DirectoryProvider`?


<!-- Sent from Reviewable.io -->

2023-07-13 19:51 UTC, AnonymousWalker commented
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 340 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FlVsO66jOcRTElc_A:-N_FlVsO66jOcRTElc_B:b-wbjxs7) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L340)):*
> ```Kotlin
>         narration.hasRedo.subscribe {
>             hasRedo = it
>         }
> ```

can we update these properties directly from these method calls: `undo(), redo()` and maybe `resetChapter()` in `NarrationBodyViewModel`? I am not sure if we need a publish subject for this, as what I am seeing is quite a sequential update



_Code snippet:_
```Kotlin
fun undo() {
        narration.undo()
        
        // update "hasUndo" here instead of waiting for sendHistoryHasActions() from the publish subject
        
        recordPause = false
        recordStart = recordedVerses.isEmpty()
        recordResume = recordedVerses.isNotEmpty()
    }
```


<!-- Sent from Reviewable.io -->

2023-07-13 19:53 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 11 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FnpmQ9X5727v-ESVY:-N_FnpmQ9X5727v-ESVZ:b24f23h) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L11)):*
> ```Kotlin
>     val redoStack = ArrayDeque<NarrationAction>()
> 
>     fun execute(
> ```

I see the class name is *___History* but we have a method named `execute()` in it. Should the execution be performed within `narration.execute()` and the history only stores the action itself?


<!-- Sent from Reviewable.io -->

2023-07-13 19:54 UTC, AnonymousWalker commented
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 9 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FoNcf9VwKoqnEL4Ea:-N_FoNcf9VwKoqnEL4Eb:baaw7pu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L9)):*
> ```Kotlin
> internal class NarrationHistory {
>     val undoStack = ArrayDeque<NarrationAction>()
>     val redoStack = ArrayDeque<NarrationAction>()
> ```

don't forget these are private ;)


<!-- Sent from Reviewable.io -->

2023-07-13 20:19 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Fu1o72_keoWj916TJ:-N_Fu1o72_keoWj916TK:bypo9xy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L15)):*
> ```Kotlin
> import java.io.File
> 
> private const val HISTORY_FILE_NAME = "narration"
> ```

should we have two separate constants? one with .json and the other with .pcm?


<!-- Sent from Reviewable.io -->

2023-07-13 20:20 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 17 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FuHsS3VveRtS6ROX7:-N_FuHsS3VveRtS6ROX8:b30q5xw) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L17)):*
> ```Kotlin
> private const val HISTORY_FILE_NAME = "narration"
> 
> class Narration (
> ```

this class looks more like a use case/activity than a data entity


<!-- Sent from Reviewable.io -->

2023-07-14 08:23 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Fu1o72_keoWj916TJ:-N_IJlnI0WuRvXp7pIhv:b-e7esbb) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L15)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

should we have two separate constants? one with .json and the other with .pcm?
</blockquote></details>

I'm not sure. This is a common name without extension for both files.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 17 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FuHsS3VveRtS6ROX7:-N_IK2B85rZ6pKln360n:b-tcelny) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L17)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

this class looks more like a use case/activity than a data entity
</blockquote></details>

Narration class is not a data class apparently. It's more a model with its own state.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 9 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FoNcf9VwKoqnEL4Ea:-N_IKMBgBW32am4WaoD3:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L9)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

don't forget these are private ;)
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt` line 11 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FnpmQ9X5727v-ESVY:-N_IKrNJ5xSeNI5_IDBm:b-hrffs5) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/NarrationHistory.kt#L11)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

I see the class name is *___History* but we have a method named `execute()` in it. Should the execution be performed within `narration.execute()` and the history only stores the action itself?
</blockquote></details>

Well we need an execute method in history class, because it adds this action to the undo stack. And since we handle actions to the history it's better to delegate action execution to it as well.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 644 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FkjRsAafIrUYeIIHj:-N_IOqnW9PC7mYnIKYn0:bshokwy) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L644)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

could we place this method in `DirectoryProvider`?
</blockquote></details>

moved this to DirectoryProvider. But I still need this method in ProjectFilesAccessor
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt` line 340 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FlVsO66jOcRTElc_A:-N_IUL7dBtNHzzRAvUaM:b-qgn0j9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/NarrationBody.kt#L340)):*
<details><summary><i>Previously, AnonymousWalker (Tony Tran) wrote…</i></summary><blockquote>

can we update these properties directly from these method calls: `undo(), redo()` and maybe `resetChapter()` in `NarrationBodyViewModel`? I am not sure if we need a publish subject for this, as what I am seeing is quite a sequential update
</blockquote></details>

I need to update hasUndo/hasRedo not only here, but also on every action. That's why I moved it to a subscribe. But I realized that I'm emitting hasUndo/hasRedo and activeVerses at the same time, so I merged it into one PublishSubject and one subscribe method, where I update them altogether.


<!-- Sent from Reviewable.io -->

2023-07-14 13:00 UTC, AnonymousWalker commented
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 644 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FkjRsAafIrUYeIIHj:-N_JTtltBUA7_5_hrfLv:b-vzlp4p) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L644)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

moved this to DirectoryProvider. But I still need this method in ProjectFilesAccessor
</blockquote></details>

please omit the change I suggested, as Joe suggested, since DirectoryProvider would serve down to the project level. 


<!-- Sent from Reviewable.io -->

2023-07-14 15:19 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 15 files reviewed, 6 unresolved discussions (waiting on @AnonymousWalker)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt` line 644 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FkjRsAafIrUYeIIHj:-N_Jz8V2CpMqtJ_rCild:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/resourcecontainer/project/ProjectFilesAccessor.kt#L644)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

please omit the change I suggested, as Joe suggested, since DirectoryProvider would serve down to the project level. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-14 17:36 UTC, jsarabia reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 15 files reviewed, 13 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Fu1o72_keoWj916TJ:-N_JFWnE16GG7whDSXY2:bjrovda) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L15)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

I'm not sure. This is a common name without extension for both files.
</blockquote></details>

it doesn't make sense for a variable called HISTORY to be set to the string "narration"

I'd rather HISTORY_FILE_NAME = "narration_history"
and CHAPTER_NARRATION_FILE_NAME = "chapter_narration"
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 17 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FuHsS3VveRtS6ROX7:-N_FxJIpBKzys24-Rq1X:bau3v5k) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L17)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Narration class is not a data class apparently. It's more a model with its own state.
</blockquote></details>

(presumably Tony's comment is regarding the package location, and might be better attached to the package line, but I agree with him- it belongs in the domain package. Probably domain/narration)

This is because it is not a data type, which is what the data package is meant for.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 35 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JGLX40J_Yt80u2kZ3:-N_JGLX40J_Yt80u2kZ4:bkdojgf) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L35)):*
> ```Kotlin
>         private set
> 
>     private val verses = mutableListOf<VerseNode>()
> ```

This should be inside an object; let's call it ChapterRepresentation or something like that
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 37 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JGUei2_VUZYIUFnmN:-N_JGUei2_VUZYIUFnmO:bxyl146) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L37)):*
> ```Kotlin
>     private val verses = mutableListOf<VerseNode>()
> 
>     private val mapper = ObjectMapper().registerKotlinModule()
> ```

This should move into the ChapterRepresentation class, as that class is what is serializable
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 39 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JHSVR0loenE-sgReh:-N_JHSVR0loenE-sgRei:besnn5t) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L39)):*
> ```Kotlin
>     private val mapper = ObjectMapper().registerKotlinModule()
> 
>     val activeVerses = PublishSubject.create<List<VerseNode>>()
> ```

This should be provided via the ChapterRepresentation class
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 92 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JnN8O6SDDW_zXTX-J:-N_JnN8O6SDDW_zXTX-K:bgkzk7e) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L92)):*
> ```Kotlin
>         verses.getOrNull(verseIndex)?.end = workingAudio.totalFrames
>         serializeVerses()
>     }
> ```

Probably also a function of the ChapterRepresentation
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 162 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JnaGtEkbntYWi90Pf:-N_JnaGtEkbntYWi90Pg:b-98lvj2) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L162)):*
> ```Kotlin
>                 it.createNewFile()
>                 it.writeText("[]")
>             }
> ```

I don't feel like we should be writing raw json ourselves, and this should be handled by jackson
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 189 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Jnnoz7TRrRPmKnZrb:-N_Jnnoz7TRrRPmKnZrc:b-92tlgz) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L189)):*
> ```Kotlin
>             sendActiveVerses()
>         }
>     }
> ```

ChapterRepresentation class
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 201 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_KSvl7-GHQPIf3Pj14:-N_KSvl7-GHQPIf3Pj15:b1fc2ee) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L201)):*
> ```Kotlin
>     }
> 
>     private fun appendCuesToWorkingAudio(cues: Map<String, File>) {
> ```

A cue is a location and a label marking off a part of audio, so the variable name here doesn't make sense given the data type.

Since we use this datatype in several places, it's also probably best to typedef it to give it a type with a name that makes more sense?

I suspect that this is a collection of verse segments indexed by cue labels.


<!-- Sent from Reviewable.io -->

2023-07-17 09:59 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 0 of 15 files reviewed, 13 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 15 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Fu1o72_keoWj916TJ:-N_Y2ZGaAibPsLQdVBIY:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L15)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

it doesn't make sense for a variable called HISTORY to be set to the string "narration"

I'd rather HISTORY_FILE_NAME = "narration_history"
and CHAPTER_NARRATION_FILE_NAME = "chapter_narration"
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 17 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_FuHsS3VveRtS6ROX7:-N_Y2anQ2XOJt5Qm3EaC:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/186016803fb588e41c2f3b0c5313bf74583d2f0d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L17)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

(presumably Tony's comment is regarding the package location, and might be better attached to the package line, but I agree with him- it belongs in the domain package. Probably domain/narration)

This is because it is not a data type, which is what the data package is meant for.
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 35 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JGLX40J_Yt80u2kZ3:-N_Y2lqP3TchM7MY9nfS:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L35)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should be inside an object; let's call it ChapterRepresentation or something like that
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 37 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JGUei2_VUZYIUFnmN:-N_Y5BdR8yLWoa_uZw9-:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L37)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should move into the ChapterRepresentation class, as that class is what is serializable
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 39 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JHSVR0loenE-sgReh:-N_Y6x48Bhew9apLq1BJ:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L39)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should be provided via the ChapterRepresentation class
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 92 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JnN8O6SDDW_zXTX-J:-N_YA5tE5CbdtFDuVqCN:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L92)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Probably also a function of the ChapterRepresentation
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 162 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_JnaGtEkbntYWi90Pf:-N_YGO_S2bqZfe_QmjTB:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L162)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't feel like we should be writing raw json ourselves, and this should be handled by jackson
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 189 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Jnnoz7TRrRPmKnZrb:-N_YGRA9E-8n0hFD6S1b:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L189)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

ChapterRepresentation class
</blockquote></details>

Done.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt` line 201 at r3](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_KSvl7-GHQPIf3Pj14:-N_YH6No-LxatJ5X7uF4:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/2d7aeb4df13e5236288e6ee41ace577b6ddae23d/common/src/main/kotlin/org/wycliffeassociates/otter/common/data/narration/Narration.kt#L201)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

A cue is a location and a label marking off a part of audio, so the variable name here doesn't make sense given the data type.

Since we use this datatype in several places, it's also probably best to typedef it to give it a type with a name that makes more sense?

I suspect that this is a collection of verse segments indexed by cue labels.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-17 13:02 UTC, jsarabia requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 15 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 65 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Ynhps3VbS1PnuwCU9:-N_Ynhps3VbS1PnuwCUA:b6qsyog) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L65)):*
> ```Kotlin
>     }
> 
>     fun loadFromSerializedVerses() {
> ```

Wouldn't we just want this to happen when the object is constructed and thus part of its initialization? This could then be private
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 77 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YntENEEDhRGX8ad8B:-N_YntENEEDhRGX8ad8C:b-hhdi6s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L77)):*
> ```Kotlin
>     }
> 
>     fun sendActiveVerses() {
> ```

Why is this public? it feels like it should only be called when a verse is added
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_YoE0p925HloZuNtwr:bysv7at) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
> ```Kotlin
>     }
> 
>     fun finalizeVerse(verseIndex: Int = activeVerses.lastIndex) {
> ```

This should just take in a verse node, and an index, and overwrite the verse node at the location in the array (the number of verses in a chapter is fixed). Thus it is not "finalize verse" but rather "update verse"


<!-- Sent from Reviewable.io -->

2023-07-18 10:21 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 15 files reviewed, 9 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 65 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_Ynhps3VbS1PnuwCU9:-N_cW4Gh9yrHlFswmsqm:b-moa0lc) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L65)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Wouldn't we just want this to happen when the object is constructed and thus part of its initialization? This could then be private
</blockquote></details>

I can't just load it on initialization, because there is scenario when I don't want to load it from history file. Like loading from selected chapter take.
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 77 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YntENEEDhRGX8ad8B:-N_cUHdWEJ1Tlp-NybGB:b-9e1e8s) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L77)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Why is this public? it feels like it should only be called when a verse is added
</blockquote></details>

Not only when added. Any time when verses change (on verse added, on undo, on redo, on initial load, on verse edited)
___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_cVFSh6AuUs7KTCSGz:bx4ip2y) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

This should just take in a verse node, and an index, and overwrite the verse node at the location in the array (the number of verses in a chapter is fixed). Thus it is not "finalize verse" but rather "update verse"
</blockquote></details>

finalizing a verse is updating the end position of it. What you mean is "replace verse".


<!-- Sent from Reviewable.io -->

2023-07-20 12:14 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_nCIBI19BlmkGxG9A_:b-kyw3tu) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

finalizing a verse is updating the end position of it. What you mean is "replace verse".
</blockquote></details>

replaceVerse is fine; my reasoning behind the term update is because the verse is kind of the index in the array and setting a new node there is updating the value of the verse.

Either way, the point is, I think it is better (and more extensible to future operations) to just replace the verse node rather than mutate the state of what's there?


<!-- Sent from Reviewable.io -->

2023-07-20 13:09 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_nPtP87a34MdXE4JDU:b-896fix) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

replaceVerse is fine; my reasoning behind the term update is because the verse is kind of the index in the array and setting a new node there is updating the value of the verse.

Either way, the point is, I think it is better (and more extensible to future operations) to just replace the verse node rather than mutate the state of what's there?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-21 12:48 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker and @mXaln)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_sTz2c-2OjQmTJJ2Sb:bd74115) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
<details><summary><i>Previously, mXaln (Maxim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I feel like it misses the point of refactoring the function if the function itself is creating the object and reaching into the list to pull out the last verse.

I was proposing that the function took in the VerseNode with the appropriate start and end positions that was to replace what was stored at the index. Such that this function had no association with "finalizing" a particular action, but simply overwriting the verse node and announcing that the list had changed.


<!-- Sent from Reviewable.io -->

2023-07-21 13:20 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker and @jsarabia)

___
*[`common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt` line 81 at r5](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-N_YoE0p925HloZuNtwq:-N_sask6BL5KT_sPEq5U:byjmich) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/4ef92877893c0ccae5a61bdeca9719f17d43eb2e/common/src/main/kotlin/org/wycliffeassociates/otter/common/domain/narration/ChapterRepresentation.kt#L81)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I feel like it misses the point of refactoring the function if the function itself is creating the object and reaching into the list to pull out the last verse.

I was proposing that the function took in the VerseNode with the appropriate start and end positions that was to replace what was stored at the index. Such that this function had no association with "finalizing" a particular action, but simply overwriting the verse node and announcing that the list had changed.
</blockquote></details>

I don't get it


<!-- Sent from Reviewable.io -->

2023-07-21 13:53 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/775#-:-N_siQsu5X_ET7PeFCr5:bnfp4nl)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @AnonymousWalker)



<!-- Sent from Reviewable.io -->

2023-07-21 13:53 UTC, merged