Duplicate verses bug fix (OT-754)
Bible-Translation-Tools/otter pull request #894
Opened 2023-11-20 14:24 UTC by mXaln

2023-11-20 16:59 UTC, AnonymousWalker requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @mXaln)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt` line 127 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894#-Njhefz--Luj9qbDzBno:-Njhefz--Luj9qbDzBnp:b-1qod4n) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/98458495c8deacdccf6b9b25ea1ab928a368fde9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L127)):*
> ```Kotlin
>                         }
>                     } catch (e: Exception) {
>                         log.info("Manifest doesn't exist, so no changes needed. Project : $project.")
> ```

does this mean the `metadata.path` directory exists but it's empty, hence the exception? I'm trying to guess which Manifest the error message implies
___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt` line 477 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894#-Njhe3A537EQxB6j9O4p:-Njhe3A537EQxB6j9O4q:b-cznfd3) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/98458495c8deacdccf6b9b25ea1ab928a368fde9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L477)):*
> ```Kotlin
>                     )
> 
>                     if (workbookDescriptor == null) {
> ```

I recall we have already caught the duplicate insertion inside the `insertWorkbookDescriptor()` method below. If that doesn't suffice, please let me know.


<!-- Sent from Reviewable.io -->

2023-11-21 09:22 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt` line 127 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894#-Njhefz--Luj9qbDzBno:-NjlAJeE36-imKZyR2M2:b7e81gg) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/98458495c8deacdccf6b9b25ea1ab928a368fde9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L127)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

does this mean the `metadata.path` directory exists but it's empty, hence the exception? I'm trying to guess which Manifest the error message implies
</blockquote></details>

Yes, you are right. The directory exists, but manifest not. This happens with new projects, that were never opened. For example, when you create a Narration project, all the books don't have manifests, until you open each separately. And if you delete the project, it will throw an exception for empty ones.


<!-- Sent from Reviewable.io -->

2023-11-21 09:27 UTC, mXaln reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt` line 477 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894#-Njhe3A537EQxB6j9O4p:-NjlBHRd9dekSL-zhICX:b-1sbumj) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/98458495c8deacdccf6b9b25ea1ab928a368fde9/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/persistence/repositories/CollectionRepository.kt#L477)):*
<details><summary><i>Previously, AnonymousWalker (Tony) wrote…</i></summary><blockquote>

I recall we have already caught the duplicate insertion inside the `insertWorkbookDescriptor()` method below. If that doesn't suffice, please let me know.
</blockquote></details>

Yes, we ignore duplicate workbook descriptor insertions. But here, by checking existence of workbook descriptor, I also avoid duplication project content.


<!-- Sent from Reviewable.io -->

2023-11-21 13:01 UTC, AnonymousWalker approved these changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/894)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-21 13:55 UTC, merged