Narration verse marker resize fix (OT-784)
Bible-Translation-Tools/otter pull request #920
Opened 2023-12-05 18:15 UTC by darrellcolehill

Binds to the VerseMarkerControl prefHeight

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920)

2023-12-08 19:04 UTC, AnonymousWalker approved these changes

2023-12-11 13:39 UTC, jsarabia requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt` line 55 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920#-NlO5Xxs25XzHofTZJTF:-NlO5XxtCk0Jd8QZ4S5j:b-51iwi) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f33066f80096a2fdf678a876057132b9c536779a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt#L55)):*
> ```Kotlin
>                     startYProperty().bind(this@region.layoutYProperty())
>                     endXProperty().bind(this@region.widthProperty().minus(MARKER_AREA_WIDTH / 2))
>                     endYProperty().bind(this@VerseMarkerControl.prefHeightProperty())
> ```

what is your intention here and how does it work?

(Because, you are not setting a prefHeight after all)


<!-- Sent from Reviewable.io -->

2023-12-11 18:33 UTC, darrellcolehill reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt` line 55 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920#-NlO5Xxs25XzHofTZJTF:-NlO7nY700xk7lZvYeVs:b-g1o6i) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/f33066f80096a2fdf678a876057132b9c536779a/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/markers/VerseMarkerControl.kt#L55)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

what is your intention here and how does it work?

(Because, you are not setting a prefHeight after all)
</blockquote></details>

This mainly came from observing how we are binding each VerseMarkerControl's prefHeightProperty to the VerseMarkerLayer.heightProperty in the VerseMarkerLayer class. Basically, I want the height of the line to be the same height of the verseMarkerLayer, which I can get through the VerseMarkerControl's prefHeightProperty. 

I was actually expecting to be able change the endYProperty binding to something like "endYProperty().bind(this@stackPane.heightProperty())". If I had to take a guess as to why that does not work, I would say that it is because the stackPane is the left side of a borderPane, and that it is being resized based off of the width. So since the stackPane is not being resized as expected, neither is the region/line. 


<!-- Sent from Reviewable.io -->

2023-12-11 20:54 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/920#-:-NlPeCXS1PwzfukLqFqP:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-11 20:54 UTC, merged