Shows narration verse and titles correctly
Bible-Translation-Tools/otter pull request #924
Opened 2023-12-06 20:30 UTC by AnonymousWalker

2023-12-07 15:52 UTC, darrellcolehill requested changes
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AnonymousWalker and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/TeleprompterView.kt` line 82 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924#-Nl3y8A32v2rfFvjRbcw:-Nl3y8A32v2rfFvjRbcx:bqe2ep1) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cdad08395ae8264d481b1982392d9c1fa3800ac0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/TeleprompterView.kt#L82)):*
> ```Kotlin
>                     } else {
>                         MessageFormat.format(
>                             messages["currentTitle"],
> ```

Not sure if this is intended or not, but when I go to record a book for the first time (let's say Genesis), pause while recording the book title, then scroll, the sticky verse will say "Current: Chapter 1" and not "Current: Genesis"


<!-- Sent from Reviewable.io -->

2023-12-07 16:36 UTC, AnonymousWalker reviewed
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/TeleprompterView.kt` line 82 at r1](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924#-Nl3y8A32v2rfFvjRbcw:-Nl47WEF4un_796KumlT:b-803vl9) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/cdad08395ae8264d481b1982392d9c1fa3800ac0/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/narration/TeleprompterView.kt#L82)):*
<details><summary><i>Previously, darrellcolehill (Darrell Cole Hill) wrote…</i></summary><blockquote>

Not sure if this is intended or not, but when I go to record a book for the first time (let's say Genesis), pause while recording the book title, then scroll, the sticky verse will say "Current: Chapter 1" and not "Current: Genesis"
</blockquote></details>

thanks for the great catch! I added the cases when the user pausing/recording to show on the sticky verse


<!-- Sent from Reviewable.io -->

2023-12-07 20:20 UTC, darrellcolehill approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924)* status: all files reviewed, 1 unresolved discussion (waiting on @jsarabia)



<!-- Sent from Reviewable.io -->

2023-12-08 08:42 UTC, mXaln approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924)* status: all files reviewed, 1 unresolved discussion (waiting on @darrellcolehill and @jsarabia)



<!-- Sent from Reviewable.io -->

2023-12-11 13:40 UTC, jsarabia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924#-:-NlO5yhv9tUwaERApbu_:bnfp4nl)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @AnonymousWalker and @darrellcolehill)

___
*[`jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/NarrationTextCell.kt` line 92 at r2](https://reviewable.io/reviews/Bible-Translation-Tools/Orature/924#-Nl8oJma4BZ5c2YfXb7R:-Nl8oJma4BZ5c2YfXb7S:b-j0bmju) ([raw file](https://github.com/Bible-Translation-Tools/Orature/blob/1aa21c7aceeafbc75bd53d11c80e0037c4e50069/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/ui/components/NarrationTextCell.kt#L92)):*
> ```Kotlin
>         graphic = view.apply {
> 
>             val title = if (item.chunk.label == "verse") item.chunk.title else ""
> ```

why make this change? Type checking seems better than a string compare?


<!-- Sent from Reviewable.io -->

2023-12-11 13:41 UTC, merged